name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: stirred_souls_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
  
      - name: Decode and import certificates
        env:
          P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          MOBILEPROVISION_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          PROVISION_NAME: ${{ secrets.PROVISION_NAME }}
          PROVISION_UUID: ${{ secrets.PROVISION_UUID }}
        run: |
          echo "$P12_BASE64" | base64 --decode -o certificate.p12
          echo "$MOBILEPROVISION_BASE64" | base64 --decode -o profile.mobileprovision

          security import certificate.p12 -P "$P12_PASSWORD" -A -T /usr/bin/codesign

          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROVISION_UUID.mobileprovision
          
      - name: Install dependencies
        run: flutter pub get

      - name: Enable iOS build
        run: flutter build ios --release --no-codesign

      - name: Archive IPA
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive \
                     archive

      - name: Export IPA
        run: |
          cd ios
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>compileBitcode</key>
          	<false/>
          	<key>destination</key>
          	<string>export</string>
          	<key>method</key>
          	<string>release-testing</string>
          	<key>provisioningProfiles</key>
          	<dict>
          		<key>BVLUF222S8.v-team.cn</key>
          		<string>$PROVISION_UUID</string>
          	</dict>
          	<key>signingCertificate</key>
          	<string>Apple Distribution</string>
          	<key>signingStyle</key>
          	<string>manual</string>
          	<key>stripSwiftSymbols</key>
          	<true/>
          	<key>teamID</key>
          	<string>${{ secrets.DEVELOPMENT_TEAM }}</string>
          	<key>thinning</key>
          	<string>none</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build/IPA

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: stirred_souls_ipa
          path: stirred_souls_app/ios/build/IPA/*.ipa
